// <auto-generated />
namespace Chinook.EF.CodeFirst.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ScriptInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScriptInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201809190134580_ScriptInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
